all:
  hosts:
    pihole:
      ansible_host: 192.168.1.252
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/terraform_id_ed25519
    portainer:
      ansible_host: 192.168.1.133
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/external
puppet_agents:
  hosts:
    pihole:
    portainer: