- name: Pihole setup and custom DNS
  hosts: pihole
  strategy: free
  become_method: sudo
  become: yes
  gather_facts: yes
  roles:
    - role: HomeSecExplorer.pihole
      vars:
        hseph_install: no
        hseph_uninstall: no
        hseph_update: no
        hseph_configure: yes
        hseph_os_check: yes
        hseph_pw_plain: password
        hseph_pihole_blocklist:
          - {url: 'https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts', enable: '1', comment: 'default'}
          - {url: 'https://big.oisd.nl', enable: '1', comment: 'default'}
        hseph_upstreams:
          - '127.0.0.1#5053'
          - '127.0.0.1#5054'
          - '8.8.8.8'
          - '8.8.4.4'

- name: Deploy custom DNS records to dnsmasq.d
  hosts: pihole
  become_method: sudo
  become: yes
  gather_facts: yes
  vars:
    hseph_custom_dns_records:
      - { domain: "proxmox.lan", ip: "192.168.1.230" }
      - { domain: "pihole.lan", ip: "192.168.1.254" }
      - { domain: "torrent.lan", ip: "192.168.1.253" }
      - { domain: "jellyfin.lan", ip: "192.168.1.252" }
      - { domain: "kuma.lan", ip: "192.168.1.105" }
  tasks:
    - name: Deploy custom DNS records to dnsmasq.d
      template:
        src: ../templates/custom-dns.conf.j2
        dest: /etc/dnsmasq.d/99-custom-dns.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart pihole-FTL
  handlers:
    - name: Restart pihole-FTL
      ansible.builtin.systemd:
        name: pihole-FTL
        state: restarted
